import { addDoc, collection, deleteDoc, doc, onSnapshot, serverTimestamp, Timestamp, updateDoc, type DocumentData, type FirestoreError } from 'firebase/firestore'
import { db } from '../firebase/config.ts'
import { inventoryCategories, inventoryConditions, type InventoryFormData, type InventoryItem } from '../types/inventory.ts'
const items = (uid: string) => collection(db, 'users', uid, 'inventory')
const item = (uid: string, id: string) => doc(db, 'users', uid, 'inventory', id)
const timestamp = (data: DocumentData, key: string) => data[key] instanceof Timestamp ? data[key] as Timestamp : null
const string = (data: DocumentData, key: string) => typeof data[key] === 'string' ? data[key] : ''
function mapInventory(id: string, data: DocumentData): InventoryItem { return { id, name: string(data, 'name'), category: inventoryCategories.includes(data.category) ? data.category : 'Other', description: string(data, 'description'), quantity: typeof data.quantity === 'number' ? Math.max(0, Math.floor(data.quantity)) : 1, location: string(data, 'location'), condition: inventoryConditions.includes(data.condition) ? data.condition : 'Good', purchaseDate: timestamp(data, 'purchaseDate')?.toDate().toISOString().slice(0, 10) ?? '', purchasePrice: typeof data.purchasePrice === 'number' ? Math.max(0, data.purchasePrice) : null, serialNumber: string(data, 'serialNumber'), notes: string(data, 'notes'), qrCode: string(data, 'qrCode') || `studentos://inventory/${id}`, createdAt: timestamp(data, 'createdAt'), updatedAt: timestamp(data, 'updatedAt') } }
function dateValue(date: string) { const value = new Date(`${date}T12:00:00`); return date && !Number.isNaN(value.getTime()) ? Timestamp.fromDate(value) : null }
function payload(data: InventoryFormData, qrCode: string) { return { ...data, name: data.name.trim(), description: data.description.trim(), quantity: Math.max(0, Math.floor(Number(data.quantity) || 0)), location: data.location.trim(), purchaseDate: dateValue(data.purchaseDate), purchasePrice: data.purchasePrice === null ? null : Math.max(0, Number(data.purchasePrice) || 0), serialNumber: data.serialNumber.trim(), notes: data.notes.trim(), qrCode } }
export function subscribeToInventory(uid: string, next: (items: InventoryItem[]) => void, error: (reason: FirestoreError) => void) { return onSnapshot(items(uid), (snapshot) => next(snapshot.docs.map((entry) => mapInventory(entry.id, entry.data())).sort((a, b) => a.name.localeCompare(b.name))), error) }
export function subscribeToInventoryItem(uid: string, id: string, next: (item: InventoryItem | null) => void, error: (reason: FirestoreError) => void) { return onSnapshot(item(uid, id), (snapshot) => next(snapshot.exists() ? mapInventory(snapshot.id, snapshot.data()) : null), error) }
export async function createInventoryItem(uid: string, data: InventoryFormData) { const reference = await addDoc(items(uid), { ...payload(data, ''), createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); await updateDoc(reference, { qrCode: `studentos://inventory/${reference.id}` }); return reference }
export async function updateInventoryItem(uid: string, id: string, data: InventoryFormData, qrCode: string) { return updateDoc(item(uid, id), { ...payload(data, qrCode), updatedAt: serverTimestamp() }) }
export async function deleteInventoryItem(uid: string, id: string) { return deleteDoc(item(uid, id)) }
