import type { CalendarEvent } from '../types/calendar.ts'
import type { Project } from '../types/project.ts'
import type { StudySession } from '../types/studySession.ts'
import type { Subject } from '../types/subject.ts'
import type { Task } from '../types/task.ts'

export type StudentContext = { subjects: Array<{ id: string; name: string; code: string }>; tasks: Array<{ id: string; title: string; status: string; priority: string; dueDate: string | null; subjectId: string | null }>; projects: Array<{ id: string; name: string; status: string; dueDate: string | null }>; study: { todayMinutes: number; weekMinutes: number }; events: Array<{ id: string; title: string; startAt: string }> }
function dateText(value: { toDate: () => Date } | null) { return value ? value.toDate().toISOString() : null }
export function buildStudentContext(subjects: Subject[], tasks: Task[], projects: Project[], sessions: StudySession[], events: CalendarEvent[]): StudentContext { const start = new Date(); start.setHours(0, 0, 0, 0); const week = new Date(start); week.setDate(week.getDate() - week.getDay()); return { subjects: subjects.map((subject) => ({ id: subject.id, name: subject.name, code: subject.code })), tasks: tasks.map((task) => ({ id: task.id, title: task.title, status: task.status, priority: task.priority, dueDate: dateText(task.dueDate), subjectId: task.subjectId })), projects: projects.map((project) => ({ id: project.id, name: project.name, status: project.status, dueDate: dateText(project.dueDateTimestamp) })), study: { todayMinutes: sessions.filter((session) => session.completed && session.startedAt.toDate() >= start).reduce((total, session) => total + session.actualMinutes, 0), weekMinutes: sessions.filter((session) => session.completed && session.startedAt.toDate() >= week).reduce((total, session) => total + session.actualMinutes, 0) }, events: events.map((event) => ({ id: event.id, title: event.title, startAt: event.startAt.toDate().toISOString() })) } }
