import { useEffect, useState } from 'react'
import { BookOpenCheck, Plus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../context/useAuth.ts'
import { subscribeToReviewers } from '../../services/reviewerService.ts'
import type { Reviewer } from '../../types/reviewer.ts'
import { getFirebaseErrorMessage } from '../../utils/firebaseError.ts'

export function SubjectReviewersPreview({ subjectId }: { subjectId: string }) { const { user } = useAuth(); const [reviewers, setReviewers] = useState<Reviewer[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { if (!user?.uid) return; return subscribeToReviewers(user.uid, (items) => { setReviewers(items.filter((item) => item.subjectId === subjectId)); setLoading(false) }, (reason) => { setError(getFirebaseErrorMessage(reason, 'Reviewers could not be loaded right now.')); setLoading(false) }) }, [subjectId, user?.uid]); return <article className="detail-notes-card"><div className="detail-task-card-heading"><span className="detail-task-icon"><BookOpenCheck size={18} /></span><div><p className="panel-eyebrow">Active recall</p><h2>Reviewers</h2></div></div>{loading ? <p className="detail-task-muted">Loading reviewers...</p> : error ? <p className="detail-task-muted">{error}</p> : reviewers.length === 0 ? <p className="detail-task-muted">No reviewers linked to this subject yet.</p> : <div className="subject-notes-preview-list">{reviewers.slice(0, 3).map((reviewer) => <Link to={`/reviewer/${reviewer.id}`} key={reviewer.id}><strong>{reviewer.title}</strong><small>{reviewer.description || 'Open reviewer'}</small></Link>)}</div>}<div className="detail-notes-actions"><Link className="dashboard-panel-link" to={`/reviewer?subjectId=${encodeURIComponent(subjectId)}`}>View all</Link><Link className="dashboard-panel-link" to={`/reviewer?new=true&subjectId=${encodeURIComponent(subjectId)}`}><Plus size={13} /> Create</Link></div></article> }
