import { useEffect, useState } from 'react'
import { ArrowLeft, FileText, Pencil, Pin, Trash2 } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { NoteForm } from '../components/notes/NoteForm.tsx'
import { Toast } from '../components/subjects/Toast.tsx'
import { DeleteTaskDialog } from '../components/tasks/DeleteTaskDialog.tsx'
import { useAuth } from '../context/useAuth.ts'
import { subscribeToSubjects } from '../services/subjectService.ts'
import { deleteNote, subscribeToNotes, updateNote } from '../services/noteService.ts'
import type { Note, NoteFormData } from '../types/note.ts'
import type { Subject } from '../types/subject.ts'
import { getFirebaseErrorMessage } from '../utils/firebaseError.ts'

export function NoteDetails() { const { user } = useAuth(); const { noteId } = useParams(); const navigate = useNavigate(); const [note, setNote] = useState<Note | null>(null); const [subjects, setSubjects] = useState<Subject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [formOpen, setFormOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState(false); const [toast, setToast] = useState<{ message: string; tone: 'success' | 'error' } | null>(null)
  useEffect(() => { if (!user?.uid || !noteId) return; return subscribeToNotes(user.uid, (notes) => { const found = notes.find((item) => item.id === noteId); setNote(found || null); setLoading(false); if (!found) setError('This note could not be found.') }, (e) => { setError(getFirebaseErrorMessage(e, 'We could not load this note.')); setLoading(false) }) }, [noteId, user?.uid]); useEffect(() => { if (!user?.uid) return; return subscribeToSubjects(user.uid, setSubjects, () => setSubjects([])) }, [user?.uid])
  async function save(data: NoteFormData) { if (!user?.uid || !note) return; setSaving(true); try { await updateNote(user.uid, note.id, data); setFormOpen(false); setToast({ message: 'Note updated.', tone: 'success' }) } catch (e) { setToast({ message: getFirebaseErrorMessage(e, 'We could not update this note.'), tone: 'error' }) } finally { setSaving(false) } }
  async function remove() { if (!user?.uid || !note) return; setDeleting(true); try { await deleteNote(user.uid, note.id); navigate('/notes', { replace: true }) } catch (e) { setToast({ message: getFirebaseErrorMessage(e, 'We could not delete this note.'), tone: 'error' }); setDeleting(false) } }
  if (loading) return <div className="subject-details-loading"><div className="detail-skeleton" /></div>; if (error || !note) return <section className="subjects-feedback subjects-feedback--error subject-detail-error"><FileText size={25} /><h2>Note unavailable</h2><p>{error || 'This note could not be found.'}</p><Link className="secondary-button" to="/notes"><ArrowLeft size={15} /> Back to notes</Link></section>
  const subject = note.subjectId ? subjects.find((item) => item.id === note.subjectId) : undefined
  return <div className="note-details-page"><Link className="back-to-subjects" to="/notes"><ArrowLeft size={16} /> All notes</Link><section className="note-detail-header"><span className="note-card-icon"><FileText size={23} /></span><div><p className="dashboard-eyebrow">Note</p><h1>{note.title}</h1><p>{subject?.name || (note.subjectId ? 'Deleted Subject' : 'General note')}</p></div><div className="subject-details-actions"><button className="secondary-button" type="button" onClick={() => setFormOpen(true)}><Pencil size={15} /> Edit</button><button className="danger-outline-button" type="button" onClick={() => setDeleteOpen(true)}><Trash2 size={15} /> Delete</button></div></section><article className="note-detail-content"><div className="note-detail-meta">{note.isPinned && <span><Pin size={14} /> Pinned</span>}{note.tags.map((tag) => <span key={tag}>#{tag}</span>)}<small>Updated {note.updatedAt?.toDate().toLocaleDateString() || 'recently'}</small></div><p>{note.content || 'No content added.'}</p></article>{formOpen && <NoteForm note={note} subjects={subjects} saving={saving} onClose={() => setFormOpen(false)} onSubmit={save} />}{deleteOpen && <DeleteTaskDialog task={{ id: note.id, title: note.title, description: '', subjectId: null, projectId: null, type: 'Other', priority: 'Low', status: 'Pending', dueDate: null, estimatedMinutes: null, reminderEnabled: false, reminderAt: null, createdAt: null, updatedAt: null, completedAt: null }} deleting={deleting} onCancel={() => setDeleteOpen(false)} onConfirm={remove} />}{toast && <Toast message={toast.message} tone={toast.tone} onClose={() => setToast(null)} />}</div>
}
