import { useEffect, useState } from 'react'
import { FolderKanban, Plus, Search } from 'lucide-react'
import { DeleteTaskDialog } from '../components/tasks/DeleteTaskDialog.tsx'
import { ProjectCard } from '../components/projects/ProjectCard.tsx'
import { ProjectForm } from '../components/projects/ProjectForm.tsx'
import { Toast } from '../components/subjects/Toast.tsx'
import { useAuth } from '../context/useAuth.ts'
import { subscribeToSubjects } from '../services/subjectService.ts'
import { subscribeToTasks } from '../services/taskService.ts'
import { createProject, deleteProject, subscribeToProjects, updateProject } from '../services/projectService.ts'
import type { Project, ProjectFormData } from '../types/project.ts'
import type { Subject } from '../types/subject.ts'
import type { Task } from '../types/task.ts'
import { getFirebaseErrorMessage } from '../utils/firebaseError.ts'

export function Projects() { const { user } = useAuth(); const userId = user?.uid; const [projects, setProjects] = useState<Project[]>([]); const [subjects, setSubjects] = useState<Subject[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Project | null>(null); const [deleteTarget, setDeleteTarget] = useState<Project | null>(null); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState(false); const [toast, setToast] = useState<{ message: string; tone: 'success' | 'error' } | null>(null)
  useEffect(() => { if (!userId) return; return subscribeToProjects(userId, (next) => { setProjects(next); setLoading(false) }, (e) => { setError(getFirebaseErrorMessage(e, 'We could not load your projects.')); setLoading(false) }) }, [userId]); useEffect(() => { if (!userId) return; const a = subscribeToSubjects(userId, setSubjects, () => setSubjects([])); const b = subscribeToTasks(userId, setTasks, () => setTasks([])); return () => { a(); b() } }, [userId])
  const subjectMap = new Map(subjects.map((subject) => [subject.id, subject])); const q = search.trim().toLowerCase(); const visible = projects.filter((project) => !q || `${project.name} ${project.description} ${project.category}`.toLowerCase().includes(q)); const taskCount = (project: Project) => tasks.filter((task) => task.projectId === project.id).length; const progress = (project: Project) => { const linked = tasks.filter((task) => task.projectId === project.id); return linked.length ? Math.round((linked.filter((task) => task.status === 'Completed').length / linked.length) * 100) : project.progress }
  async function save(data: ProjectFormData) { if (!userId) return; setSaving(true); try { if (editing) await updateProject(userId, editing.id, data); else await createProject(userId, data); setFormOpen(false); setEditing(null); setToast({ message: editing ? 'Project updated.' : 'Project added.', tone: 'success' }) } catch (e) { setToast({ message: getFirebaseErrorMessage(e, 'We could not save this project.'), tone: 'error' }) } finally { setSaving(false) } }
  async function remove() { if (!userId || !deleteTarget) return; setDeleting(true); try { await deleteProject(userId, deleteTarget.id); setDeleteTarget(null); setToast({ message: 'Project deleted.', tone: 'success' }) } catch (e) { setToast({ message: getFirebaseErrorMessage(e, 'We could not delete this project.'), tone: 'error' }) } finally { setDeleting(false) } }
  return <div className="projects-page"><section className="module-page-header"><div><p className="dashboard-eyebrow">Make progress visible</p><h1>Projects</h1><p>Keep bigger pieces of work moving in one place.</p></div><button className="primary-button" type="button" onClick={() => { setEditing(null); setFormOpen(true) }}><Plus size={17} /> Add project</button></section><label className="projects-search"><Search size={16} /><input type="search" value={search} placeholder="Search projects" aria-label="Search projects" onChange={(e) => setSearch(e.target.value)} /></label>{error ? <section className="subjects-feedback subjects-feedback--error"><FolderKanban size={25} /><h2>Projects unavailable</h2><p>{error}</p></section> : loading ? <div className="subject-grid"><div className="subject-card subject-card--skeleton" /><div className="subject-card subject-card--skeleton" /><div className="subject-card subject-card--skeleton" /></div> : projects.length === 0 ? <section className="subjects-feedback"><div className="empty-subject-icon"><FolderKanban size={27} /></div><h2>No projects yet</h2><p>Start a project to make progress easier to see.</p><button className="primary-button" type="button" onClick={() => setFormOpen(true)}><Plus size={17} /> Add project</button></section> : visible.length === 0 ? <section className="subjects-feedback"><h2>No projects match your search</h2><p>Try another search term.</p></section> : <div className="project-grid">{visible.map((project) => <ProjectCard key={project.id} project={project} subject={project.subjectId ? subjectMap.get(project.subjectId) : undefined} taskCount={taskCount(project)} calculatedProgress={progress(project)} onEdit={(item) => { setEditing(item); setFormOpen(true) }} onDelete={setDeleteTarget} />)}</div>}{formOpen && <ProjectForm key={editing?.id ?? 'new-project'} project={editing} subjects={subjects} saving={saving} onClose={() => setFormOpen(false)} onSubmit={save} />}{deleteTarget && <DeleteTaskDialog task={{ id: deleteTarget.id, title: deleteTarget.name, description: '', subjectId: null, projectId: null, type: 'Other', priority: 'Low', status: 'Pending', dueDate: null, estimatedMinutes: null, reminderEnabled: false, reminderAt: null, createdAt: null, updatedAt: null, completedAt: null }} deleting={deleting} onCancel={() => setDeleteTarget(null)} onConfirm={remove} />}{toast && <Toast message={toast.message} tone={toast.tone} onClose={() => setToast(null)} />}</div> }
