import { useEffect, useState } from 'react'
import { Timestamp } from 'firebase/firestore'
import { ArrowLeft, CheckCircle2, Circle, RotateCcw } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../context/useAuth.ts'
import { subscribeToQuestions, subscribeToReviewer } from '../services/reviewerService.ts'
import { createQuizAttempt } from '../services/quizService.ts'
import { questionTypes, type Question, type QuestionType, type QuizAnswer, type Reviewer } from '../types/reviewer.ts'
import { getFirebaseErrorMessage } from '../utils/firebaseError.ts'
import { questionTypeLabel } from '../utils/reviewer.ts'

function shuffle<T>(items: T[]) { return [...items].sort(() => Math.random() - 0.5) }
function normalize(value: string) { return value.trim().toLowerCase() }

export function ReviewerQuiz() {
  const { reviewerId } = useParams(); const { user } = useAuth(); const uid = user?.uid; const [reviewer, setReviewer] = useState<Reviewer | null>(null); const [questions, setQuestions] = useState<Question[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [count, setCount] = useState(10); const [selectedTypes, setSelectedTypes] = useState<QuestionType[]>([...questionTypes]); const [shuffleQuestions, setShuffleQuestions] = useState(true); const [shuffleChoices, setShuffleChoices] = useState(true); const [quizQuestions, setQuizQuestions] = useState<Question[]>([]); const [answers, setAnswers] = useState<Record<string, string>>({}); const [current, setCurrent] = useState(0); const [startedAt, setStartedAt] = useState<Date | null>(null); const [submitted, setSubmitted] = useState(false); const [result, setResult] = useState<{ score: number; answers: QuizAnswer[] } | null>(null); const [saving, setSaving] = useState(false)
  useEffect(() => { if (!uid || !reviewerId) return; const a = subscribeToReviewer(uid, reviewerId, (item) => { setReviewer(item); setLoading(false); if (!item) setError('This reviewer could not be found.') }, (reason) => { setError(getFirebaseErrorMessage(reason, 'We could not load this reviewer.')); setLoading(false) }); const b = subscribeToQuestions(uid, reviewerId, setQuestions, (reason) => setError(getFirebaseErrorMessage(reason, 'Questions could not be loaded.'))); return () => { a(); b() } }, [reviewerId, uid])
  const availableQuestions = questions.filter((question) => selectedTypes.includes(question.type));
  function startQuiz() { const selected = shuffleQuestions ? shuffle(availableQuestions) : [...availableQuestions]; const prepared = selected.slice(0, Math.max(1, Math.min(count, selected.length))).map((question) => ({ ...question, choices: shuffleChoices && question.type === 'multiple_choice' ? shuffle(question.choices) : [...question.choices] })); setQuizQuestions(prepared); setAnswers({}); setCurrent(0); setStartedAt(new Date()); setSubmitted(false); setResult(null) }
  function setAnswer(value: string) { const question = quizQuestions[current]; if (question) setAnswers((previous) => ({ ...previous, [question.id]: value })) }
  async function submitQuiz() { if (!uid || !reviewer || !startedAt || saving) return; if (!window.confirm('Submit this quiz now?')) return; const answerSnapshot = quizQuestions.map((question): QuizAnswer => { const userAnswer = answers[question.id] || ''; return { questionId: question.id, userAnswer, correctAnswer: question.correctAnswer, isCorrect: normalize(userAnswer) === normalize(question.correctAnswer) } }); const score = answerSnapshot.filter((answer) => answer.isCorrect).length; setSaving(true); try { await createQuizAttempt(uid, { reviewerId: reviewer.id, subjectId: reviewer.subjectId, startedAt: Timestamp.fromDate(startedAt), completedAt: Timestamp.now(), score, totalQuestions: quizQuestions.length, percentage: quizQuestions.length ? Math.round(score / quizQuestions.length * 100) : 0, answers: answerSnapshot }); setResult({ score, answers: answerSnapshot }); setSubmitted(true) } catch (reason) { setError(getFirebaseErrorMessage(reason, 'The quiz attempt could not be saved.')) } finally { setSaving(false) } }
  if (loading) return <div className="reviewer-page"><div className="module-loading">Loading quiz...</div></div>
  if (error || !reviewer || !reviewerId) return <div className="reviewer-page"><section className="subjects-feedback subjects-feedback--error"><h2>Quiz unavailable</h2><p>{error || 'This reviewer could not be found.'}</p><Link className="secondary-button" to="/reviewer"><ArrowLeft size={15} /> Back to reviewers</Link></section></div>
  if (submitted && result) return <QuizResults reviewer={reviewer} questions={quizQuestions} result={result} onRetry={() => { setSubmitted(false); setResult(null); setQuizQuestions([]) }} />
  if (!quizQuestions.length) return <div className="quiz-page"><Link className="back-link" to={`/reviewer/${reviewer.id}`}><ArrowLeft size={15} /> Back to reviewer</Link><section className="quiz-setup"><p className="dashboard-eyebrow">Quiz setup</p><h1>{reviewer.title}</h1><p>Choose how you want to practise. Stored question order will not be changed.</p><div className="quiz-setup-grid"><label>Question count<input type="number" min="1" max={Math.max(1, availableQuestions.length)} value={Math.min(count, Math.max(1, availableQuestions.length))} onChange={(event) => setCount(Math.max(1, Number(event.target.value)))} /></label><div><span className="quiz-label">Question types</span>{questionTypes.map((type) => <label className="quiz-check" key={type}><input type="checkbox" checked={selectedTypes.includes(type)} onChange={(event) => setSelectedTypes(event.target.checked ? [...selectedTypes, type] : selectedTypes.filter((item) => item !== type))} /><span>{questionTypeLabel(type)}</span></label>)}</div></div><label className="quiz-check"><input type="checkbox" checked={shuffleQuestions} onChange={(event) => setShuffleQuestions(event.target.checked)} /><span>Shuffle questions</span></label><label className="quiz-check"><input type="checkbox" checked={shuffleChoices} onChange={(event) => setShuffleChoices(event.target.checked)} /><span>Shuffle multiple-choice options</span></label>{availableQuestions.length === 0 ? <p className="quiz-warning">No questions match the selected types.</p> : <button className="primary-button" type="button" onClick={startQuiz}>Start quiz ({availableQuestions.length} available)</button>}</section></div>
  const question = quizQuestions[current]; const selectedAnswer = answers[question.id] || ''; return <div className="quiz-page"><div className="quiz-topline"><Link className="back-link" to={`/reviewer/${reviewer.id}`}><ArrowLeft size={15} /> Exit quiz</Link><span>{current + 1} of {quizQuestions.length}</span></div><section className="quiz-card"><div className="quiz-progress"><span style={{ width: `${(current + 1) / quizQuestions.length * 100}%` }} /></div><div className="quiz-question-heading"><span>{questionTypeLabel(question.type)}</span><small>{Math.round((current + 1) / quizQuestions.length * 100)}% complete</small></div><h1>{question.question}</h1>{question.type === 'multiple_choice' ? <div className="quiz-choices">{question.choices.map((choice, index) => <label className={selectedAnswer === choice ? 'quiz-choice quiz-choice--selected' : 'quiz-choice'} key={`${choice}-${index}`}><input type="radio" name={question.id} checked={selectedAnswer === choice} onChange={() => setAnswer(choice)} /><span className="quiz-choice-letter">{String.fromCharCode(65 + index)}</span><span>{choice}</span></label>)}</div> : question.type === 'true_false' ? <div className="quiz-choices">{['True', 'False'].map((choice) => <label className={selectedAnswer === choice ? 'quiz-choice quiz-choice--selected' : 'quiz-choice'} key={choice}><input type="radio" name={question.id} checked={selectedAnswer === choice} onChange={() => setAnswer(choice)} /><span className="quiz-choice-letter">{choice === 'True' ? 'T' : 'F'}</span><span>{choice}</span></label>)}</div> : <input className="quiz-identification-input" value={selectedAnswer} placeholder="Type your answer" onChange={(event) => setAnswer(event.target.value)} />}<div className="quiz-actions"><button className="secondary-button" type="button" disabled={current === 0} onClick={() => setCurrent((value) => value - 1)}>Previous</button>{current < quizQuestions.length - 1 ? <button className="primary-button" type="button" onClick={() => setCurrent((value) => value + 1)}>Next</button> : <button className="primary-button" type="button" disabled={saving} onClick={() => void submitQuiz()}>{saving ? 'Saving...' : 'Submit quiz'}</button>}</div></section></div>
}

function QuizResults({ reviewer, questions, result, onRetry }: { reviewer: Reviewer; questions: Question[]; result: { score: number; answers: QuizAnswer[] }; onRetry: () => void }) { const percentage = questions.length ? Math.round(result.score / questions.length * 100) : 0; const answerMap = new Map(result.answers.map((answer) => [answer.questionId, answer])); return <div className="quiz-page"><Link className="back-link" to={`/reviewer/${reviewer.id}`}><ArrowLeft size={15} /> Back to reviewer</Link><section className="quiz-results-hero"><CheckCircle2 size={32} /><p className="dashboard-eyebrow">Quiz complete</p><h1>{result.score} / {questions.length}</h1><strong>{percentage}%</strong><p>{percentage >= 80 ? 'Strong work. Keep the momentum going.' : 'Review the answers below and try again when ready.'}</p><button className="primary-button" type="button" onClick={onRetry}><RotateCcw size={15} /> Try again</button></section><section className="answer-review"><h2>Answer review</h2>{questions.map((question, index) => { const answer = answerMap.get(question.id); return <article key={question.id}><div className={answer?.isCorrect ? 'answer-review-icon answer-review-icon--correct' : 'answer-review-icon'}>{answer?.isCorrect ? <CheckCircle2 size={16} /> : <Circle size={16} />}</div><div><span>Question {index + 1}</span><h3>{question.question}</h3><p>Your answer: <strong>{answer?.userAnswer || 'No answer'}</strong></p><p>Correct answer: <strong>{question.correctAnswer}</strong></p>{question.explanation && <small>{question.explanation}</small>}</div></article> })}</section></div> }
