import { useEffect, useState, type FormEvent } from 'react'
import { BookOpenCheck, Plus, Search, Trash2, X } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAuth } from '../context/useAuth.ts'
import { createReviewer, deleteReviewer, getQuestions, subscribeToReviewers } from '../services/reviewerService.ts'
import { subscribeToSubjects } from '../services/subjectService.ts'
import { emptyReviewer, type Reviewer, type ReviewerFormData } from '../types/reviewer.ts'
import type { Subject } from '../types/subject.ts'
import { getFirebaseErrorMessage } from '../utils/firebaseError.ts'
import { Toast } from '../components/subjects/Toast.tsx'

export function Reviewer() {
  const { user } = useAuth(); const uid = user?.uid; const [params] = useSearchParams(); const [reviewers, setReviewers] = useState<Reviewer[]>([]); const [subjects, setSubjects] = useState<Subject[]>([]); const [counts, setCounts] = useState<Record<string, number>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [formOpen, setFormOpen] = useState(() => params.get('new') === 'true'); const [form, setForm] = useState<ReviewerFormData>(() => ({ ...emptyReviewer(), subjectId: params.get('subjectId') || null })); const [saving, setSaving] = useState(false); const [deleteTarget, setDeleteTarget] = useState<Reviewer | null>(null); const [deleting, setDeleting] = useState(false); const [toast, setToast] = useState<{ message: string; tone: 'success' | 'error' } | null>(null)
  useEffect(() => { if (!uid) return; return subscribeToReviewers(uid, (items) => { setReviewers(items); setLoading(false) }, (reason) => { setError(getFirebaseErrorMessage(reason, 'Reviewers could not be loaded.')); setLoading(false) }) }, [uid])
  useEffect(() => { if (!uid) return; let active = true; void Promise.all(reviewers.map(async (reviewer) => [reviewer.id, (await getQuestions(uid, reviewer.id)).length] as const)).then((entries) => { if (active) setCounts(Object.fromEntries(entries)) }).catch(() => undefined); return () => { active = false } }, [reviewers, uid])
  const subjectMap = new Map(subjects.map((subject) => [subject.id, subject.name])); const query = search.trim().toLowerCase(); const visible = reviewers.filter((reviewer) => !query || `${reviewer.title} ${reviewer.description} ${reviewer.subjectId ? subjectMap.get(reviewer.subjectId) : ''}`.toLowerCase().includes(query))
  useEffect(() => { if (!uid) return; return subscribeToSubjects(uid, setSubjects, () => setSubjects([])) }, [uid])
  async function save(event: FormEvent) { event.preventDefault(); if (!uid || !form.title.trim()) return; setSaving(true); try { await createReviewer(uid, form); setFormOpen(false); setForm({ ...emptyReviewer(), subjectId: params.get('subjectId') || null }); setToast({ message: 'Reviewer created.', tone: 'success' }) } catch (reason) { setToast({ message: getFirebaseErrorMessage(reason, 'We could not create this reviewer.'), tone: 'error' }) } finally { setSaving(false) } }
  async function remove() { if (!uid || !deleteTarget) return; setDeleting(true); try { await deleteReviewer(uid, deleteTarget.id); setDeleteTarget(null); setToast({ message: 'Reviewer deleted.', tone: 'success' }) } catch (reason) { setToast({ message: getFirebaseErrorMessage(reason, 'We could not delete this reviewer.'), tone: 'error' }) } finally { setDeleting(false) } }
  return <div className="reviewer-page"><section className="module-page-header"><div><p className="dashboard-eyebrow">Practice what matters</p><h1>Smart Reviewer</h1><p>Build focused review sets, quiz yourself, and learn from your attempts.</p></div><button className="primary-button" type="button" onClick={() => setFormOpen(true)}><Plus size={17} /> Create reviewer</button></section><label className="reviewer-search"><Search size={16} /><input type="search" value={search} placeholder="Search reviewers" aria-label="Search reviewers" onChange={(event) => setSearch(event.target.value)} /></label>{error ? <section className="subjects-feedback subjects-feedback--error"><BookOpenCheck size={25} /><h2>Reviewers unavailable</h2><p>{error}</p></section> : loading ? <div className="module-loading">Loading reviewers...</div> : reviewers.length === 0 ? <section className="subjects-feedback"><div className="empty-subject-icon"><BookOpenCheck size={27} /></div><h2>No reviewers yet</h2><p>Create a reviewer for a subject, exam, or topic you want to practise.</p><button className="primary-button" type="button" onClick={() => setFormOpen(true)}><Plus size={17} /> Create reviewer</button></section> : visible.length === 0 ? <section className="subjects-feedback"><h2>No reviewers match your search</h2><p>Try another search term.</p></section> : <div className="reviewer-grid">{visible.map((reviewer) => <article className="reviewer-card" key={reviewer.id}><div className="reviewer-card-icon"><BookOpenCheck size={21} /></div><div className="reviewer-card-heading"><h2>{reviewer.title}</h2><span>{counts[reviewer.id] ?? 0} questions</span></div><p>{reviewer.description || 'No description added.'}</p><div className="reviewer-card-meta"><span>{reviewer.subjectId ? subjectMap.get(reviewer.subjectId) ?? 'Deleted subject' : 'General reviewer'}</span><small>Updated {reviewer.updatedAt?.toDate().toLocaleDateString() ?? 'recently'}</small></div><div className="reviewer-card-actions"><Link className="primary-button" to={`/reviewer/${reviewer.id}`}>Open reviewer</Link><button type="button" aria-label={`Delete ${reviewer.title}`} onClick={() => setDeleteTarget(reviewer)}><Trash2 size={15} /></button></div></article>)}</div>}{formOpen && <ReviewerForm form={form} subjects={subjects} saving={saving} onChange={setForm} onClose={() => setFormOpen(false)} onSubmit={save} />}{deleteTarget && <ConfirmDelete reviewer={deleteTarget} deleting={deleting} onCancel={() => setDeleteTarget(null)} onConfirm={remove} />}{toast && <Toast message={toast.message} tone={toast.tone} onClose={() => setToast(null)} />}</div>
}

function ReviewerForm({ form, subjects, saving, onChange, onClose, onSubmit }: { form: ReviewerFormData; subjects: Subject[]; saving: boolean; onChange: (value: ReviewerFormData) => void; onClose: () => void; onSubmit: (event: FormEvent) => void }) { return <div className="modal-layer"><button className="modal-backdrop" type="button" aria-label="Close reviewer form" onClick={onClose} /><form className="module-modal" onSubmit={onSubmit}><button className="modal-close-button" type="button" aria-label="Close form" onClick={onClose}><X size={18} /></button><p className="dashboard-eyebrow">New study set</p><h2>Create reviewer</h2><label>Title<input required autoFocus value={form.title} placeholder="Database midterm reviewer" onChange={(event) => onChange({ ...form, title: event.target.value })} /></label><label>Subject<select value={form.subjectId ?? ''} onChange={(event) => onChange({ ...form, subjectId: event.target.value || null })}><option value="">General reviewer</option>{subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.name} ({subject.code})</option>)}</select></label><label>Description<textarea rows={4} value={form.description} placeholder="What should this reviewer help you practise?" onChange={(event) => onChange({ ...form, description: event.target.value })} /></label><div className="modal-actions"><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving ? 'Creating...' : 'Create reviewer'}</button></div></form></div> }
function ConfirmDelete({ reviewer, deleting, onCancel, onConfirm }: { reviewer: Reviewer; deleting: boolean; onCancel: () => void; onConfirm: () => void }) { return <div className="modal-layer"><button className="modal-backdrop" type="button" aria-label="Close confirmation" onClick={onCancel} /><section className="module-modal module-modal--small"><h2>Delete reviewer?</h2><p><strong>{reviewer.title}</strong> and its questions will be permanently removed.</p><div className="modal-actions"><button className="secondary-button" type="button" onClick={onCancel}>Cancel</button><button className="danger-button" type="button" disabled={deleting} onClick={onConfirm}>{deleting ? 'Deleting...' : 'Delete'}</button></div></section></div> }
