import { useEffect, useState, type FormEvent } from 'react'
import { X } from 'lucide-react'
import type { Subject } from '../../types/subject.ts'
import { emptyNote, type Note, type NoteFormData } from '../../types/note.ts'

type NoteFormProps = { note?: Note | null; initialSubjectId?: string | null; subjects: Subject[]; saving: boolean; onClose: () => void; onSubmit: (note: NoteFormData) => Promise<void> }
export function NoteForm({ note, initialSubjectId, subjects, saving, onClose, onSubmit }: NoteFormProps) {
  const [form, setForm] = useState<NoteFormData>(() => note ? { title: note.title, content: note.content, subjectId: note.subjectId, tags: note.tags, isPinned: note.isPinned } : { ...emptyNote(), subjectId: initialSubjectId ?? null })
  const [error, setError] = useState('')
  useEffect(() => { function escape(key: KeyboardEvent) { if (key.key === 'Escape' && !saving) onClose() }; const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; document.addEventListener('keydown', escape); return () => { document.body.style.overflow = old; document.removeEventListener('keydown', escape) } }, [onClose, saving])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (!form.title.trim()) { setError('Add a title before saving this note.'); return }; await onSubmit({ ...form, title: form.title.trim(), content: form.content.trim(), tags: form.tags.map((tag) => tag.trim()).filter(Boolean) }) }
  return <div className="modal-layer"><button className="modal-backdrop" type="button" aria-label="Close note form" onClick={saving ? undefined : onClose} /><section className="task-modal note-modal" role="dialog" aria-modal="true" aria-labelledby="note-form-title"><div className="subject-modal-header"><div><p className="dashboard-eyebrow">Capture the useful stuff</p><h2 id="note-form-title">{note ? 'Edit note' : 'Add note'}</h2></div><button className="modal-close-button" type="button" aria-label="Close note form" onClick={onClose} disabled={saving}><X size={18} /></button></div><form className="task-form" onSubmit={submit} noValidate>{error && <div className="subject-form-error" role="alert">{error}</div>}<label>Title <span>*</span><input type="text" value={form.title} placeholder="Routing ideas" onChange={(e) => setForm({ ...form, title: e.target.value })} disabled={saving} autoFocus /></label><label>Subject<select value={form.subjectId ?? ''} onChange={(e) => setForm({ ...form, subjectId: e.target.value || null })} disabled={saving}><option value="">General note</option>{subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.name} ({subject.code})</option>)}</select></label><label>Content<textarea className="note-editor" value={form.content} placeholder="Write your note..." onChange={(e) => setForm({ ...form, content: e.target.value })} disabled={saving} rows={11} /></label><label>Tags <small className="field-help">Separate tags with commas</small><input type="text" value={form.tags.join(', ')} placeholder="routing, web, ideas" onChange={(e) => setForm({ ...form, tags: e.target.value.split(',') })} disabled={saving} /></label><label className="reminder-toggle-row"><input type="checkbox" checked={form.isPinned} onChange={(e) => setForm({ ...form, isPinned: e.target.checked })} disabled={saving} /><span className="custom-checkbox" aria-hidden="true" /><span><strong>Pin this note</strong><small>Keep it at the top of your notes.</small></span></label><div className="subject-form-actions"><button className="secondary-button" type="button" onClick={onClose} disabled={saving}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving ? 'Saving...' : note ? 'Save changes' : 'Add note'}</button></div></form></section></div>
}
